compile:
	g++ main.cpp -o ../bin/pong.exe -Iinclude -Llib -lsfml-audio-s -lsfml-graphics-s -lsfml-window-s -lsfml-system-s -lopengl32 -lwinmm -lgdi32 -lfreetype -lopenal32 -lflac -lvorbisenc -lvorbisfile -lvorbis -logg -static-libgcc -static-libstdc++
